" Micheal's .vimrc
" ============================================

" Cosmetics
" ============================================


set number " show line numbers
set ruler " show column number in statusbar
syntax enable " syntax highlighting
" set cursorline " highlight the line on which the cursor is
set showmatch " highlight matching [{()}]
set incsearch " search as characters are entered
set hlsearch " highlight matches
set list " show invisibles
set listchars=eol:¬,trail:-,tab:·· " set invisibles to show
" set colorcolumn=80,73,47
set showcmd
let showedited = v:true " include + in tabline for edited buffers
let showtabnr = v:true " show tab number in tabline
let usecustomlabels = v:true
colorscheme lollipop

" Behaviors
" ============================================

set mouse=a " allow mouse to place cursor / select text
set tabstop=4 " tabs appear to be 4 long
set expandtab " tabs are spaces
set softtabstop=4 " soft tabs are 4 long
set shiftwidth=5 " autoindent only does 4 spaces instead of 8
set smartindent " does the right thing?
set lazyredraw " redraw only when we need to
filetype indent on " filetype detection and related indentation
filetype plugin on
set hidden " allows navigating away from a modified buffer
set backspace=2 " makes backspace behave normally in 8.1
set nojoinspaces " use one space instead of two after periods
set undofile " keeps track of changes across loading of files
set undodir=~/.vim/undodir " keeps undofiles in a central place

" Folding
" ============================================

" set foldmethod=syntax " enable code folding based on syntax
" set nofoldenable " ? start with nothing folded
set foldmethod=manual " enable manual code folding

augroup AutoSaveFolds " automatically save and load folds
  autocmd!
  autocmd BufWinLeave * silent! mkview
  autocmd BufWinEnter * silent! loadview
augroup END

" Auto Commands
" ============================================

" autocmd VimLeave * call SaveSess()
" autocmd VimEnter * nested call RestoreSess()

" Mappings
" ============================================

""" Leader
let mapleader=","
inoremap kj <ESC>
noremap <Leader>jk <ESC>
""" :new
nnoremap <C-W><C-N> <C-W><C-N><C-W><C-X><C-W><C-J>
""" :split vvv
nnoremap <C-W><C-S> <C-W><C-S><C-W><C-J>
""" :vsplit vvv
nnoremap <C-W><C-V> <C-W><C-V><C-W><C-L>
""" move line
nnoremap <C-J> :m +1<CR>
nnoremap <C-K> :m -2<CR>
" nnoremap <Leader>S :mksession " vvv
nnoremap <Leader>s :mksession!<CR>
""" recolors entire buffer vvv
nnoremap <silent> <F12> :syntax sync fromstart<CR>
""" In-Buffer Navigation vvv
nnoremap <Leader>n <C-D>
nnoremap <Leader>u <C-U>
""" Inter-Buffer Navigation vvv
nnoremap <silent> <C-B> :bn<CR>
nnoremap <silent> <C-F> :bp<CR>
""" Window Navigation vvv
nnoremap <Leader>h <C-W>h
nnoremap <Leader>j <C-W>j
nnoremap <Leader>k <C-W>k
nnoremap <Leader>l <C-W>l

vnoremap <Leader>m :normal ,m<CR>
vnoremap <Leader>n :normal ,n<CR>

""" Tab Navigation
nnoremap <Right> gt
nnoremap <Left> gT
nnoremap <Leader>t :%s/\s\+$//<CR>:noh<CR>

nnoremap <Leader>r :source $MYVIMRC<CR>
nnoremap <Leader>e :vsplit $MYVIMRC<CR><C-W><C-X><C-W><C-L>
nnoremap <Leader>h :noh<CR>


inoremap <Leader>r' ’
inoremap <Leader>l' ‘
inoremap <Leader>r" ”
inoremap <Leader>l" “

vnoremap <Leader>( s(")<ESC>
vnoremap <Leader>{ s{"}<ESC>
vnoremap <Leader>[ s["]<ESC>
vnoremap <Leader>< s<"><ESC>
vnoremap <Leader>" s"""<ESC>
vnoremap <Leader>' s'"'<ESC>
vnoremap <Leader>* s*"*<ESC>


" Abbreviations
" ============================================

iabbrev hte the
iabbrev teh the
